"""add manual_wins to users

Revision ID: 48bc21e93b29
Revises: 6503bcf5fa3d
Create Date: 2026-09-01 11:39:53.679460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48bc21e93b29'
down_revision: Union[str, Sequence[str], None] = '6503bcf5fa3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('manual_wins', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'manual_wins')
    # ### end Alembic commands ###
