"""add submissions_locked to cycle

Revision ID: 906216d4d402
Revises: a1b2c3d4e5f6
Create Date: 2026-08-27 11:36:59.631929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '906216d4d402'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycles', sa.Column('submissions_locked', sa.Boolean(), nullable=True))
    op.execute("UPDATE cycles SET submissions_locked = false WHERE submissions_locked IS NULL")
    op.alter_column('cycles', 'submissions_locked', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cycles', 'submissions_locked')
    # ### end Alembic commands ###
